function AssertionCheckingCaseStudyLogsSafe = importfile_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ASSERTIONCHECKINGCASESTUDYLOGSSAFE = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  ASSERTIONCHECKINGCASESTUDYLOGSSAFE = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AssertionCheckingCaseStudyLogsSafe = importfile("/home/greg/git/CAV-Assertions/matlab/AssertionCheckingCaseStudyLogs_Safe.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Apr-2022 14:37:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["testNo", "repeatNo", "agentNo", "agentID", "agentType", "agentTypeNo", "x", "y", "z", "yaw", "vel_x", "vel_y", "vel_z", "speed", "time", "sim_time", "fps"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "agentType", "EmptyFieldRule", "auto");

% Import the data
AssertionCheckingCaseStudyLogsSafe = readtable(filename, opts);

end